[package]
name = "quiche-future"
version = "0.1.0"
authors = ["Jun Ryoung Ju <junryoungju@gmail.com>"]
edition = "2018"

[lib]
name = "quiche_future"
path = "lib.rs"

[dependencies]
quiche = "*"
async-std = { version = "*", features = ["unstable"] }
anyhow = "*"
futures = "*"
log = "*"
ring = "*"